import { Callback, Context } from 'aws-lambda';
import { S3Event } from '../types/s3Event';
import fetch from 'node-fetch';

import { Post } from './post';

export const handler = async (
  event: S3Event,
  context: Context,
  callback: Callback
) => {
  context.callbackWaitsForEmptyEventLoop = false;

  console.log(JSON.stringify(event));

  const postTemplateGerneratorName = 'tweet-summarizer';

  const post = new Post(event);

  if (post.isGeneratedBy(postTemplateGerneratorName)) {
    const message = `This post is generated by post template gernerator. Skiped.`;
    console.log(
      JSON.stringify({
        message,
        event,
        postTemplateGerneratorName,
      })
    );
    // Error
    callback(null, message);
  }

  const response = await fetch('https://github.com/');
  const body = await response.text();

  console.log(body);

  const res = {
    statusCode: 200,
  };

  console.log(`env: ${process.env.env}`);
};
